// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yzwmckszkfjzobpvpifv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inl6d21ja3N6a2Zqem9icHZwaWZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzNDAxMjcsImV4cCI6MjA2ODkxNjEyN30.xA596DKJATpFngY4kGGeYhzjZUQ_uf3XFn8QKEpp2zk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});